services:
  web:
    restart: always
    build: .
    ports:
      - "127.0.0.1:3000:3000"
    networks:
      - external_network
    volumes:
      - ./.config:/misskey-media-proxy/.config:ro

networks:
  external_network:
